export const products = [
  {
    "id": 10,
    "name": "Python AI & ML Course",
    "slug": "python-ai-ml",
    "description": "Master artificial intelligence and machine learning with Python. Covers deep learning, NLP, computer vision, and real-world projects.",
    "shortDesc": "AI & Machine Learning with Python",
    "price": 499000,
    "originalPrice": 999000,
    "category": "course",
    "image": "/products/course.jpg",
    "rating": 4.9,
    "reviews": 789,
    "badge": "Bestseller",
    "features": [
      "120+ Hours Video",
      "30+ AI Projects",
      "GPU Cloud Credits",
      "Certificate",
      "Job Preparation"
    ],
    "downloads": 31201,
    "fileSize": "25 GB",
    "format": "Video / Notebooks / Datasets",
    "version": "2026 Updated",
    "stock": 13
  },
  {
    "id": 4,
    "name": "Web Dev Mastery Course",
    "slug": "web-dev-mastery",
    "description": "Complete full-stack web development course from zero to hero. Covers HTML, CSS, JavaScript, React, Node.js, databases, and deployment. 80+ hours of video content.",
    "shortDesc": "Full-stack web development course",
    "price": 399000,
    "originalPrice": 799000,
    "category": "course",
    "image": "/products/course.jpg",
    "rating": 4.7,
    "reviews": 567,
    "badge": "Bestseller",
    "features": [
      "80+ Hours Video",
      "50+ Projects",
      "Certificate",
      "Discord Community",
      "Mentor Support"
    ],
    "downloads": 23406,
    "fileSize": "15 GB",
    "format": "Video / Project Files",
    "version": "2026 Updated",
    "stock": 6
  },
  {
    "id": 7,
    "name": "CodeMaster IDE Pro",
    "slug": "codemaster-ide-pro",
    "description": "Next-generation code editor with AI autocomplete, multi-language support, integrated terminal, and powerful debugging tools.",
    "shortDesc": "AI-powered code editor",
    "price": 249000,
    "originalPrice": 449000,
    "category": "software",
    "image": "/products/software.jpg",
    "rating": 4.7,
    "reviews": 421,
    "badge": "New",
    "features": [
      "AI Code Completion",
      "50+ Language Support",
      "Git Integration",
      "Real-time Collaboration",
      "Custom Themes"
    ],
    "downloads": 18202,
    "fileSize": "1.8 GB",
    "format": "Windows / Mac / Linux",
    "version": "2.0.0",
    "stock": 0
  },
  {
    "id": 3,
    "name": "NeonDash UI Kit",
    "slug": "neondash-ui-kit",
    "description": "Premium dashboard UI template with 200+ components, dark mode, responsive layouts, and ready-to-use React components. Perfect for SaaS applications.",
    "shortDesc": "Premium React dashboard UI kit",
    "price": 199000,
    "originalPrice": 349000,
    "category": "template",
    "image": "/products/template.jpg",
    "rating": 4.9,
    "reviews": 312,
    "badge": "New",
    "features": [
      "200+ Components",
      "React & Vue Versions",
      "Dark & Light Mode",
      "Figma Source Files",
      "Lifetime Updates"
    ],
    "downloads": 15603,
    "fileSize": "180 MB",
    "format": "React / Vue / Figma",
    "version": "1.5.0",
    "stock": 17
  },
  {
    "id": 15,
    "name": "E-commerce Starter Kit",
    "slug": "ecommerce-starter",
    "description": "Complete e-commerce template with product catalog, cart, checkout, payment integration, and admin panel. Built with Next.js and Stripe.",
    "shortDesc": "Full-stack e-commerce template",
    "price": 349000,
    "originalPrice": 599000,
    "category": "template",
    "image": "/products/template.jpg",
    "rating": 4.8,
    "reviews": 345,
    "badge": "Bestseller",
    "features": [
      "Stripe Payments",
      "Admin Dashboard",
      "SEO Optimized",
      "Multi-language",
      "Email Notifications"
    ],
    "downloads": 14202,
    "fileSize": "280 MB",
    "format": "Next.js + Stripe",
    "version": "2.3.0",
    "stock": 5
  },
  {
    "id": 1,
    "name": "ProSuite Design Studio",
    "slug": "prosuite-design-studio",
    "description": "Professional design suite with AI-powered tools for creating stunning graphics, illustrations, and UI designs. Includes 500+ templates and real-time collaboration.",
    "shortDesc": "AI-powered professional design suite",
    "price": 299000,
    "originalPrice": 499000,
    "category": "software",
    "image": "/products/software.jpg",
    "rating": 4.8,
    "reviews": 234,
    "badge": "Bestseller",
    "features": [
      "AI-Powered Design Tools",
      "Real-time Collaboration",
      "500+ Premium Templates",
      "Cloud Storage 100GB",
      "Priority Support"
    ],
    "downloads": 12500,
    "fileSize": "2.4 GB",
    "format": "Windows / Mac / Linux",
    "version": "3.2.1",
    "stock": 15
  },
  {
    "id": 11,
    "name": "SEO PowerTools Plugin",
    "slug": "seo-powertools",
    "description": "All-in-one SEO plugin for WordPress with keyword analysis, schema markup, sitemap generation, and competitor analysis dashboard.",
    "shortDesc": "Complete WordPress SEO toolkit",
    "price": 149000,
    "originalPrice": 249000,
    "category": "plugin",
    "image": "/products/plugin.jpg",
    "rating": 4.6,
    "reviews": 267,
    "badge": null,
    "features": [
      "Keyword Analysis",
      "Schema Markup",
      "XML Sitemaps",
      "Competitor Analysis",
      "Social Media Preview"
    ],
    "downloads": 11304,
    "fileSize": "18 MB",
    "format": "WordPress Plugin",
    "version": "5.0.2",
    "stock": 5
  },
  {
    "id": 16,
    "name": "Mobile App Design Course",
    "slug": "mobile-app-design",
    "description": "Learn to design beautiful mobile apps from scratch. Covers UI/UX principles, Figma, prototyping, design systems, and handoff to developers.",
    "shortDesc": "Mobile UI/UX design course",
    "price": 279000,
    "originalPrice": 499000,
    "category": "course",
    "image": "/products/course.jpg",
    "rating": 4.6,
    "reviews": 234,
    "badge": null,
    "features": [
      "60+ Hours Video",
      "Figma Projects",
      "Design System Template",
      "Certificate",
      "Portfolio Projects"
    ],
    "downloads": 10503,
    "fileSize": "12 GB",
    "format": "Video / Figma Files",
    "version": "2026 Updated",
    "stock": 10
  },
  {
    "id": 9,
    "name": "AdminPro React Template",
    "slug": "adminpro-react",
    "description": "Feature-rich React admin dashboard template with 100+ pages, charts, tables, forms, and authentication. Built with Material Design.",
    "shortDesc": "React admin dashboard template",
    "price": 179000,
    "originalPrice": 299000,
    "category": "template",
    "image": "/products/template.jpg",
    "rating": 4.6,
    "reviews": 203,
    "badge": "Sale",
    "features": [
      "100+ Pages",
      "Material Design",
      "Redux Integration",
      "RTL Support",
      "TypeScript"
    ],
    "downloads": 9801,
    "fileSize": "220 MB",
    "format": "React + TypeScript",
    "version": "3.1.0",
    "stock": 21
  },
  {
    "id": 2,
    "name": "Digital Marketing Mastery",
    "slug": "digital-marketing-mastery",
    "description": "Comprehensive ebook covering SEO, social media marketing, email campaigns, and conversion optimization. Updated for 2026 with AI marketing strategies.",
    "shortDesc": "Complete digital marketing guide for 2026",
    "price": 149000,
    "originalPrice": 249000,
    "category": "ebook",
    "image": "/products/ebook.jpg",
    "rating": 4.6,
    "reviews": 189,
    "badge": "Sale",
    "features": [
      "350+ Pages",
      "Real Case Studies",
      "AI Marketing Chapter",
      "Bonus Templates",
      "Free Updates"
    ],
    "downloads": 8901,
    "fileSize": "45 MB",
    "format": "PDF / EPUB / MOBI",
    "version": "2nd Edition",
    "stock": 7
  },
  {
    "id": 13,
    "name": "CloudSync Backup Pro",
    "slug": "cloudsync-backup",
    "description": "Enterprise-grade cloud backup solution with end-to-end encryption, scheduled backups, version history, and multi-platform support.",
    "shortDesc": "Encrypted cloud backup solution",
    "price": 189000,
    "originalPrice": 349000,
    "category": "software",
    "image": "/products/software.jpg",
    "rating": 4.5,
    "reviews": 178,
    "badge": "Sale",
    "features": [
      "E2E Encryption",
      "Auto Scheduling",
      "Version History",
      "Multi-Platform",
      "1TB Storage"
    ],
    "downloads": 8902,
    "fileSize": "890 MB",
    "format": "Windows / Mac / Linux / Mobile",
    "version": "6.0.1",
    "stock": 9
  },
  {
    "id": 12,
    "name": "Motion Graphics Kit",
    "slug": "motion-graphics-kit",
    "description": "300+ animated elements, transitions, and title templates for video editing. Compatible with After Effects, Premiere Pro, and DaVinci Resolve.",
    "shortDesc": "300+ animated video elements",
    "price": 199000,
    "originalPrice": 399000,
    "category": "asset",
    "image": "/products/assets.jpg",
    "rating": 4.7,
    "reviews": 156,
    "badge": "New",
    "features": [
      "300+ Animations",
      "After Effects & Premiere",
      "4K Resolution",
      "Easy Customization",
      "Tutorial Included"
    ],
    "downloads": 7601,
    "fileSize": "2.1 GB",
    "format": "AE / PR / DR",
    "version": "1.2",
    "stock": 24
  },
  {
    "id": 5,
    "name": "SpeedBoost WordPress Plugin",
    "slug": "speedboost-wp",
    "description": "Advanced WordPress performance optimization plugin. Lazy loading, CDN integration, image compression, caching, and Core Web Vitals optimization.",
    "shortDesc": "WordPress performance optimizer",
    "price": 99000,
    "originalPrice": 199000,
    "category": "plugin",
    "image": "/products/plugin.jpg",
    "rating": 4.5,
    "reviews": 145,
    "badge": "Sale",
    "features": [
      "Auto Image Optimization",
      "CDN Integration",
      "Smart Caching",
      "Core Web Vitals",
      "WooCommerce Support"
    ],
    "downloads": 6700,
    "fileSize": "12 MB",
    "format": "WordPress Plugin",
    "version": "4.1.0",
    "stock": 5
  },
  {
    "id": 14,
    "name": "UX Research Handbook",
    "slug": "ux-research-handbook",
    "description": "Practical guide to user experience research methods, usability testing, personas, journey mapping, and data-driven design decisions.",
    "shortDesc": "Practical UX research methods guide",
    "price": 119000,
    "originalPrice": 179000,
    "category": "ebook",
    "image": "/products/ebook.jpg",
    "rating": 4.4,
    "reviews": 112,
    "badge": null,
    "features": [
      "320+ Pages",
      "Research Templates",
      "Case Studies",
      "Interview Scripts",
      "Analysis Frameworks"
    ],
    "downloads": 4800,
    "fileSize": "52 MB",
    "format": "PDF / EPUB / MOBI",
    "version": "2nd Edition",
    "stock": 16
  },
  {
    "id": 6,
    "name": "IconCraft Premium Pack",
    "slug": "iconcraft-premium",
    "description": "5000+ premium vector icons in 20 categories. Available in SVG, PNG, and icon font formats. Perfect for web and mobile applications.",
    "shortDesc": "5000+ premium vector icons",
    "price": 79000,
    "originalPrice": 159000,
    "category": "asset",
    "image": "/products/assets.jpg",
    "rating": 4.4,
    "reviews": 98,
    "badge": null,
    "features": [
      "5000+ Icons",
      "SVG & PNG Formats",
      "20 Categories",
      "Regular Updates",
      "Commercial License"
    ],
    "downloads": 4200,
    "fileSize": "350 MB",
    "format": "SVG / PNG / Icon Font",
    "version": "2.0",
    "stock": 30
  },
  {
    "id": 8,
    "name": "Startup Growth Playbook",
    "slug": "startup-growth-playbook",
    "description": "The ultimate guide for startup founders. Covers fundraising, product-market fit, growth hacking, team building, and scaling strategies.",
    "shortDesc": "Essential startup founder guide",
    "price": 129000,
    "originalPrice": 199000,
    "category": "ebook",
    "image": "/products/ebook.jpg",
    "rating": 4.3,
    "reviews": 76,
    "badge": null,
    "features": [
      "280+ Pages",
      "Founder Interviews",
      "Financial Templates",
      "Growth Frameworks",
      "Pitch Deck Templates"
    ],
    "downloads": 3400,
    "fileSize": "38 MB",
    "format": "PDF / EPUB",
    "version": "1st Edition",
    "stock": 18
  },
  {
    "id": 17,
    "name": "p",
    "slug": "p",
    "category": "software",
    "price": 998,
    "originalPrice": null,
    "description": "No description provided.",
    "shortDesc": "p",
    "format": "Digital Download",
    "version": "1.0.0",
    "fileSize": "1",
    "image": "/products/software.jpg",
    "rating": 5,
    "reviews": 0,
    "downloads": 0,
    "stock": 99,
    "badge": "New",
    "features": [
      "Instant Activation",
      "Lifetime updates"
    ]
  },
  {
    "id": 18,
    "name": "Test Product Created",
    "slug": "test-product-created",
    "category": "software",
    "price": 150000,
    "originalPrice": null,
    "description": "No description provided.",
    "shortDesc": "Test Product Created",
    "format": "Digital Download",
    "version": "1.0.0",
    "fileSize": "Unknown",
    "image": "/products/software.jpg",
    "rating": 5,
    "reviews": 0,
    "downloads": 1,
    "stock": 9,
    "badge": "New",
    "features": [
      "Instant Activation",
      "Lifetime updates"
    ]
  },
  {
    "id": 19,
    "name": "p",
    "slug": "p",
    "category": "ebook",
    "price": 10000,
    "originalPrice": null,
    "description": "No description provided.",
    "shortDesc": "p",
    "format": "Digital Download",
    "version": "1.0.0",
    "fileSize": "10",
    "image": "/products/ebook.jpg",
    "rating": 5,
    "reviews": 0,
    "downloads": 0,
    "stock": 99,
    "badge": "New",
    "features": [
      "Instant Activation",
      "Lifetime updates"
    ]
  }
];
