export const products = [
  {
    "id": 2,
    "name": "Digital Marketing Mastery",
    "slug": "digital-marketing-mastery",
    "description": "Comprehensive ebook covering SEO, social media marketing, email campaigns, and conversion optimization. Updated for 2026 with AI marketing strategies.",
    "shortDesc": "Complete digital marketing guide for 2026",
    "price": 149000,
    "originalPrice": 249000,
    "category": "ebook",
    "image": "/products/ebook.jpg",
    "rating": 4.6,
    "reviews": 189,
    "badge": "Sale",
    "features": [
      "350+ Pages",
      "Real Case Studies",
      "AI Marketing Chapter",
      "Bonus Templates",
      "Free Updates"
    ],
    "downloads": 8901,
    "fileSize": "45 MB",
    "format": "PDF / EPUB / MOBI",
    "stock": 7,
    "code": "PRD-0002",
    "useVariations": false,
    "stockForm": "Manual",
    "editStockMode": false,
    "accountsStock": "",
    "termsAndConditions": "Syarat & Ketentuan Lisensi Digital berlaku.",
    "requireNote": "Tidak",
    "cashbackType": "Potongan Nominal",
    "cashbackValue": 0,
    "profit": 0,
    "bulkingMode": 0,
    "wholesaleTiers": [],
    "isVisible": true
  },
  {
    "id": 12,
    "name": "Motion Graphics Kit",
    "slug": "motion-graphics-kit",
    "description": "300+ animated elements, transitions, and title templates for video editing. Compatible with After Effects, Premiere Pro, and DaVinci Resolve.",
    "shortDesc": "300+ animated video elements",
    "price": 199000,
    "originalPrice": 399000,
    "category": "asset",
    "image": "/products/assets.jpg",
    "rating": 4.7,
    "reviews": 156,
    "badge": "New",
    "features": [
      "300+ Animations",
      "After Effects & Premiere",
      "4K Resolution",
      "Easy Customization",
      "Tutorial Included"
    ],
    "downloads": 7601,
    "fileSize": "2.1 GB",
    "format": "AE / PR / DR",
    "stock": 24,
    "code": "PRD-0012",
    "useVariations": false,
    "stockForm": "Manual",
    "editStockMode": false,
    "accountsStock": "",
    "termsAndConditions": "Syarat & Ketentuan Lisensi Digital berlaku.",
    "requireNote": "Tidak",
    "cashbackType": "Potongan Nominal",
    "cashbackValue": 0,
    "profit": 0,
    "bulkingMode": 0,
    "wholesaleTiers": [],
    "isVisible": true
  },
  {
    "id": 5,
    "name": "SpeedBoost WordPress Plugin",
    "slug": "speedboost-wp",
    "description": "Advanced WordPress performance optimization plugin. Lazy loading, CDN integration, image compression, caching, and Core Web Vitals optimization.",
    "shortDesc": "WordPress performance optimizer",
    "price": 99000,
    "originalPrice": 199000,
    "category": "plugin",
    "image": "/products/plugin.jpg",
    "rating": 4.5,
    "reviews": 145,
    "badge": "Sale",
    "features": [
      "Auto Image Optimization",
      "CDN Integration",
      "Smart Caching",
      "Core Web Vitals",
      "WooCommerce Support"
    ],
    "downloads": 6700,
    "fileSize": "12 MB",
    "format": "WordPress Plugin",
    "stock": 5,
    "code": "PRD-0005",
    "useVariations": false,
    "stockForm": "Manual",
    "editStockMode": false,
    "accountsStock": "",
    "termsAndConditions": "Syarat & Ketentuan Lisensi Digital berlaku.",
    "requireNote": "Tidak",
    "cashbackType": "Potongan Nominal",
    "cashbackValue": 0,
    "profit": 0,
    "bulkingMode": 0,
    "wholesaleTiers": [],
    "isVisible": true
  },
  {
    "id": 14,
    "name": "UX Research Handbook",
    "slug": "ux-research-handbook",
    "description": "Practical guide to user experience research methods, usability testing, personas, journey mapping, and data-driven design decisions.",
    "shortDesc": "Practical UX research methods guide",
    "price": 119000,
    "originalPrice": 179000,
    "category": "ebook",
    "image": "/products/ebook.jpg",
    "rating": 4.4,
    "reviews": 112,
    "badge": null,
    "features": [
      "320+ Pages",
      "Research Templates",
      "Case Studies",
      "Interview Scripts",
      "Analysis Frameworks"
    ],
    "downloads": 4800,
    "fileSize": "52 MB",
    "format": "PDF / EPUB / MOBI",
    "stock": 16,
    "code": "PRD-0014",
    "useVariations": false,
    "stockForm": "Manual",
    "editStockMode": false,
    "accountsStock": "",
    "termsAndConditions": "Syarat & Ketentuan Lisensi Digital berlaku.",
    "requireNote": "Tidak",
    "cashbackType": "Potongan Nominal",
    "cashbackValue": 0,
    "profit": 0,
    "bulkingMode": 0,
    "wholesaleTiers": [],
    "isVisible": true
  },
  {
    "id": 6,
    "name": "IconCraft Premium Pack",
    "slug": "iconcraft-premium",
    "description": "5000+ premium vector icons in 20 categories. Available in SVG, PNG, and icon font formats. Perfect for web and mobile applications.",
    "shortDesc": "5000+ premium vector icons",
    "price": 79000,
    "originalPrice": 159000,
    "category": "asset",
    "image": "/products/assets.jpg",
    "rating": 4.4,
    "reviews": 98,
    "badge": null,
    "features": [
      "5000+ Icons",
      "SVG & PNG Formats",
      "20 Categories",
      "Regular Updates",
      "Commercial License"
    ],
    "downloads": 4200,
    "fileSize": "350 MB",
    "format": "SVG / PNG / Icon Font",
    "stock": 30,
    "code": "PRD-0006",
    "useVariations": false,
    "stockForm": "Manual",
    "editStockMode": false,
    "accountsStock": "",
    "termsAndConditions": "Syarat & Ketentuan Lisensi Digital berlaku.",
    "requireNote": "Tidak",
    "cashbackType": "Potongan Nominal",
    "cashbackValue": 0,
    "profit": 0,
    "bulkingMode": 0,
    "wholesaleTiers": [],
    "isVisible": true
  },
  {
    "id": 8,
    "name": "Startup Growth Playbook",
    "slug": "startup-growth-playbook",
    "description": "The ultimate guide for startup founders. Covers fundraising, product-market fit, growth hacking, team building, and scaling strategies.",
    "shortDesc": "Essential startup founder guide",
    "price": 129000,
    "originalPrice": 199000,
    "category": "ebook",
    "image": "/products/ebook.jpg",
    "rating": 4.3,
    "reviews": 76,
    "badge": null,
    "features": [
      "280+ Pages",
      "Founder Interviews",
      "Financial Templates",
      "Growth Frameworks",
      "Pitch Deck Templates"
    ],
    "downloads": 3400,
    "fileSize": "38 MB",
    "format": "PDF / EPUB",
    "stock": 18,
    "code": "PRD-0008",
    "useVariations": false,
    "stockForm": "Manual",
    "editStockMode": false,
    "accountsStock": "",
    "termsAndConditions": "Syarat & Ketentuan Lisensi Digital berlaku.",
    "requireNote": "Tidak",
    "cashbackType": "Potongan Nominal",
    "cashbackValue": 0,
    "profit": 0,
    "bulkingMode": 0,
    "wholesaleTiers": [],
    "isVisible": true
  }
];
